name: owoade_brimble

services:
  buildkit:
    image: moby/buildkit
    container_name: buildkit
    privileged: true
    command: ["--addr", "tcp://0.0.0.0:1234"]
    ports:
      - "1234:1234"
    restart: unless-stopped
    networks:
      - net

  caddy:
    image: caddy:latest
    container_name: owoade_brimble_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./defaults/caddy.json:/etc/caddy/caddy.json:ro
      - caddy_data:/data
      - caddy_config:/config
    command: caddy run --config /etc/caddy/caddy.json
    networks:
      - net

  ui:
    build:
      context: ./brimble-frontend
    container_name: owoade_brimble_ui
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - net

  api:
    build:
      context: ./brimble-backend
    container_name: owoade_brimble_api
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      BUILDKIT_HOST: "tcp://buildkit:1234"
      DOCKER_BUILDKIT: "1"

    expose:
      - "3000"
    networks:
      - net

volumes:
  caddy_data:
  caddy_config:
  app_data:

networks:
  net:
    driver: bridge